<?php

namespace OuikendBundle\Repository;

/**
 * ActivitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitesRepository extends \Doctrine\ORM\EntityRepository
{
}
