OuikendBundle\Entity\Activites:
    type: entity
    table: null
    repositoryClass: OuikendBundle\Repository\ActivitesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        activite:
            type: string
            length: 255
        descriptif:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToMany:
        trips:
            targetEntity: OuikendBundle\Entity\Trips
            iversedBy: activites
            joinTable:
                name: trips_activites
                joinColumns:
                    trips_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activites_id:
                        referencedColumnName: id